<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="2" failures="0" finished="true" name="Test Run: 4" tests="2" total_time="Finished in: 14.19 secs."/>
    <test location="C:\Users\Aravi\Automation\FinalProject\CapstonePy\test_my_script.py" status="error" test="test_scenario_1" time="9.49">
        <stdout/>
        <stderr><![CDATA[service = <selenium.webdriver.chrome.service.Service object at 0x0000019B26953020>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
>           path = SeleniumManager().driver_location(options) if path is None else path

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.common.selenium_manager.SeleniumManager object at 0x0000019B27538860>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    def driver_location(self, options: BaseOptions) -> str:
        """Determines the path of the correct driver.
    
        :Args:
         - browser: which browser to get the driver path for.
        :Returns: The driver path to use
        """
    
>       browser = options.capabilities["browserName"]
E       AttributeError: 'str' object has no attribute 'capabilities'

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\selenium_manager.py:75: AttributeError

During handling of the above exception, another exception occurred:

    @pytest.fixture
    def driver():
        # Setup
>       driver = webdriver.Chrome(ChromeDriverManager().install())

test_my_script.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py:45: in __init__
    super().__init__(
..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py:51: in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

service = <selenium.webdriver.chrome.service.Service object at 0x0000019B26953020>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
            path = SeleniumManager().driver_location(options) if path is None else path
        except Exception as err:
>           msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
E           AttributeError: 'str' object has no attribute 'capabilities'

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py:40: AttributeError]]></stderr>
    </test>
    <test location="C:\Users\Aravi\Automation\FinalProject\CapstonePy\test_my_script.py" status="error" test="test_scenario_2" time="4.15">
        <stdout/>
        <stderr><![CDATA[service = <selenium.webdriver.chrome.service.Service object at 0x0000019B2696B3E0>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
>           path = SeleniumManager().driver_location(options) if path is None else path

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.common.selenium_manager.SeleniumManager object at 0x0000019B2696B590>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    def driver_location(self, options: BaseOptions) -> str:
        """Determines the path of the correct driver.
    
        :Args:
         - browser: which browser to get the driver path for.
        :Returns: The driver path to use
        """
    
>       browser = options.capabilities["browserName"]
E       AttributeError: 'str' object has no attribute 'capabilities'

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\selenium_manager.py:75: AttributeError

During handling of the above exception, another exception occurred:

    @pytest.fixture
    def driver():
        # Setup
>       driver = webdriver.Chrome(ChromeDriverManager().install())

test_my_script.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py:45: in __init__
    super().__init__(
..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py:51: in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

service = <selenium.webdriver.chrome.service.Service object at 0x0000019B2696B3E0>
options = 'C:\\Users\\Aravi\\.wdm\\drivers\\chromedriver\\win64\\119.0.6045.105\\chromedriver-win32/chromedriver.exe'

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
            path = SeleniumManager().driver_location(options) if path is None else path
        except Exception as err:
>           msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
E           AttributeError: 'str' object has no attribute 'capabilities'

..\..\..\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py:40: AttributeError]]></stderr>
    </test>
    <launch mode="run">
        <launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="CapstonePy test_my_script.py"/>
]]></launch_memento>
    </launch>
</pydev-testsuite>
